### ISSUE TITLE
Пункт 1 ЧТЗ: Изменить вывод данных в ответном файле XML от ФРМР

### ISSUE THREAD

**Issue by DmitryKamenev** [nOleg/FOMS#14]
Изменить вывод данных в тэг WorkFlowID. Необходимо в данное поле выводить наименование входящего csv пакета. Если файл со СНИЛС имеет название YM2017001, то в тэге будет -
 <WorkFlowID>YM2017001</WorkFlowID>

**Comment by nOleg** [comment]
Можешь рассчитывать  на поле WorkFlowID с именем исходящего файла

**Comment by nOleg** [comment]
Образец 
[\\192.168.0.40\public\FRMR_Output\ym19.xml](\\192.168.0.40\public\FRMR_Output\ym19.xml)
