### ISSUE TITLE
Server Reporting Services

### ISSUE THREAD

**Issue by nOleg** [nOleg/FOMS#20]
А.6.3 Состояние обработки входных файлов Форма отчета по состоянию обработки входных файлов приведена в таблице А.5. Отчет упо-рядочен по дате получения в обратном хронологическом порядке. Отчет создается с помощью гене-ратора Report Builder и выполняется с помощью SQL Server Reporting Services.

**Comment by DmitryKamenev** [comment]
Отчеты готовы
