### ISSUE TITLE
ЧТЗ 6: Формирование выгрузки xml в файл

### ISSUE THREAD

**Issue by DmitryKamenev** [nOleg/FOMS#25]
Необходимо из процедуры dbo.sp_smev_snils_request_xml_export (БД FOMS_DEV_01) получить xml и выгрузить xml в файл с кодировкой UTF-8 и с шапкой "<?xml version="1.0" encoding="UTF-8"?>".
Исходящие параметры в процедуре:
@xml - тело XML
@xml_file_name - наименование XML

Вызов процедуры для теста:
DECLARE
	@xml	xml,
	@xml_file_name	varchar(50)
	
EXEC dbo.sp_smev_snils_request_xml_export
	@xml = @xml		OUTPUT,
	@xml_file_name = @xml_file_name OUTPUT
	
SELECT @xml, @xml_file_name

**Comment by DmitryKamenev** [comment]
\\192.168.0.102\LogShipping\

**Comment by nOleg** [comment]
ExportToSMEV

**Comment by DmitryKamenev** [comment]
Сервер 192.168.0.102. БД - FOMS_DEV_01

**Comment by nOleg** [comment]
[ExportToSMEV.zip](https://github.com/nOleg/FOMS/files/1477982/ExportToSMEV.zip)


Образец стартовых параматров: "C:/Regions/" "Data Source=192.168.0.102;Initial Catalog=FOMS_DEV_01;User ID=sa;Password=!QAZ2wsx"
