### ISSUE TITLE
Добави описание отчетов

### ISSUE THREAD

**Issue by nOleg** [nOleg/FOMS#31]
```///=========Добавлены новые=================
/// <summary>
 /// Расхождение данных о медициских работниках, указанных в прикреплении и полученных от ФРМП
        /// </summary>
        PHN_INACT = 24,

         /// <summary>
        /// Расхождение данных о медициских работниках, указанных в прикреплении и полученных от ФРМП
        /// </summary>
        PHN_DEATH = 25,

         /// <summary>
        /// Расхождение данных о медициских работниках, указанных в прикреплении и полученных от ФРМП
        /// </summary>
        PHN_RATE = 26,

        /// <summary>
        /// Расхождение данных о медициских работниках, указанных в прикреплении и полученных от ФРМП
        /// </summary>
        PHN_NF = 27,

         /// <summary>
        /// Расхождение данных о медициских работниках, указанных в прикреплении и полученных от ФРМП
        /// </summary>
        POL_ISS = 28

**Comment by DmitryKamenev** [comment]
PHN_NF -	Медицинские работники, не найденные в ФРМР
PHN_DEATH -	Умершие прикреплённые ЗЛ
PHN_INACT -	Прикреплённые ЗЛ без действующей страховой принадлежности
SNILS_NF - 	ЗЛ с не найденными СНИЛС
POL_IIS -	Сведения по выпуску полисов
PHN_RATE -	Половозрастное распределение прикрепленных ЗЛ

Протоколы PHN_NF, PHN_DEATH, PHN_INACT и SNILS_NF должны формироваться аналогично как протоколы PHN или MED.

Протоколы POL_IIS и PHN_RATE должны формироваться аналогично Ф8 или СПИС. На сколько я помню, шлюз ЦС ЕРЗ дергает репортинг сервер и получается отчет и результат передается обратно. Это проверь.
