### ISSUE TITLE
Тестирование пункта 1

### ISSUE THREAD

**Issue by nOleg** [nOleg/FOMS#32]
[01225033001.txt](https://github.com/nOleg/FOMS/files/1500866/01225033001.txt)
[01696254973.txt](https://github.com/nOleg/FOMS/files/1500867/01696254973.txt)
[01796354974.txt](https://github.com/nOleg/FOMS/files/1500868/01796354974.txt)

**Comment by nOleg** [comment]
IIS 6+
Net Core 2.0
Framework 4.5
IE11
Microsoft утилита хостинга Net.Core на IIS 
https://aka.ms/dotnetcore-2-windowshosting

**Comment by DmitryKamenev** [comment]
Путь куда складывать ответный пакеты xml
\\192.168.0.204\FRMR_Output

**Comment by nOleg** [comment]
Пути  к РепортСерверным отчетам  пропишу в сетинги

**Comment by AnnaGrasmik** [comment]
Замечания по "мордочке" сайта:
1. Сделать сайт адаптивным под диагональ 17" и выше (от 1280*1024)
2. Текст Arial
3. Размер кнопок не более 150px
4. Хлебные крошки расположить под лого. Из-за того, что это блочно-строчный элемент, но нет четких границ - выглядит криво



**http://192.168.2.39/**
.mnu-line {
    margin: 5% 0 0 0;
    background: rgb(54, 54, 122);
}

.mnu li ul {
    background: rgb(54, 54, 122);
    position: absolute;
    left: 0px;
    top: 100px;
}


.ul.open-sub {
padding-left: 0px;
}




.open-sub.a.li {
    left: 0px;
    padding-left: 0px;
    width: 280px;
}


**http://192.168.2.39/Home/UploadWorkers**
При попытке загрузить файл открывается страница http://192.168.2.39/UploadFiles и выходит сообщение Object reference not set to an instance of an object.
Может пока файл не выбран сделать кнопку неактивной?

**http://192.168.2.39/Home/uploadresult**

Имена столбцов на русском языке (+)

<tr>
        <td>Код должности</td><td>Группа должностей</td>           
        <td>Сертификация</td>
        <td>Должность</td>
        <td>Медицинская</td>
        <td>Дата прекращения</td>
        <td>Тип должности</td>
        <td>Возможность прикрепления</td>          
</tr>

thead td {
    background: rgb(49, 105, 206);
    text-align: center;
    color: #ffffff;



**http://192.168.2.39/Home/BaseMonitor**

thead td {
    background: rgb(54, 54, 122);
    color: #ffffff;
    text-align: center;
}
