### ISSUE TITLE
Пункт 2 ЧТЗ. Доработка АРМ ШРС и шлюза ЦС ЕРЗ

### ISSUE THREAD

**Issue by DmitryKamenev** [nOleg/FOMS#6]
Необходимо добавить новые запросы отчетов (Протоколы актуализации) в АРМ ШРС и обработку их на шлюзе ЦС ЕРЗ.
Новые типы отчетов:
1. PHN_INACT
2. PHN_DEATH
3. PHN_RATE
4. PHN_NF

Отчет PHN_RATE должен возвращать xls-файл, аналогично с отчетом Ф8 или СПИС. 

![default](https://user-images.githubusercontent.com/33277038/32264264-ee5f1506-beee-11e7-8b87-a6aecb164a04.jpg)

**Comment by DmitryKamenev** [comment]
4.2.2 Разработка и актуализация запросов ТФОМС на получение информации о прикреплении
Отчёты по прикреплению застрахованных лиц к медицинским организациям и медицинским работникам по данным ЦС ЕРЗ, предоставляемые ТФОМС через АРМ ШРС и актуальные на 15.08.2017, перечислены в приложении Б. В дополнение к ним в компоненте формирования отчётов по БД ЦС ЕРЗ должны быть разработаны следующие отчёты, содержащие показатели, необходимые для формирования рейтинга терапевтов и перечисленные в таблице 2 Порядка предоставления сведений, необходимых для формирования рейтинга терапевтов, размещённого на корпоративном сайте Федерального фонда обязательного медицинского страхования (web.ffoms.ru) в разделе «Единый регистр застрахованных лиц (ИС ЕРЗ ОМС)» 22.09.2016:
-	отчёт по половозрастному распределению прикрепленных застрахованных лиц (код отчёта PHN_RATE);
-	отчет по умершим прикрепленным застрахованным лицам (код отчёта PHN_DEATH);
-	отчёт по прикрепленным застрахованным лицам, не имеющим действующей страховки;
-	отчёт по медицинским работникам, не найденным в ФРМР.
Формы отчётов приведены в приложении Б. Формирование отчётов должно инициироваться с помощью АРМ ШРС.

**Comment by DmitryKamenev** [comment]
Пункт Б
[ЧТЗ_на_развитие_подсистемы_ЕРЗ_24октября_v3.docx](https://github.com/nOleg/FOMS/files/1457650/_._._._._24._v3.docx)

**Comment by DmitryKamenev** [comment]
FOMS_gateway.exe - Шлюз РС

**Comment by DmitryKamenev** [comment]
После создание запроса на отчет формируется файл (*.uprmes) на 192.168.0.77 в папку C:\srz\input.

**Comment by DmitryKamenev** [comment]
Брокер сообщений информационной системы ИС ОМС сканируется папку C:\srz\input и при обнаружении файла *.uprmes он перемещается в папку C:\foms\AutoLoad\XmlInput. Далее шлюз РС (ИС ЕРЗ ОМС.Сервер обработки сообщений(36)) обрабатывается данный файл.

**Comment by DmitryKamenev** [comment]
После форматно-логический контроль ФЛК шлюза РС создается *.dat файл и маршрутизатор перемещает его на 192.168.0.78 в папку c:\foms\AutoLoad\BizTalk\In

**Comment by DmitryKamenev** [comment]
Далее BizTalk перемещает *.dat файл в Центральный сегмент единого регистра застрахованных (ЦС ЕРЗ) на 192.168.0.70 в папку C:\27\FOMS\AutoLoad\Gateway\Share\Входящие письма. Далее маршрутизатор ЦС ЕРЗ (Брокер сообщений информационной системы ИС ОМС) перемещается файл в папку C:\27\FOMS\AutoLoad\Gateway\Input. После чего шлюз ЦС ЕРЗ (ИС ОМС. Подсистема ЕРЗ. ?) обрабатывает данный файл.

**Comment by DmitryKamenev** [comment]
После обработки, файл перемещается в папку C:\27\FOMS\AutoLoad\Gateway\Reports и имеет расширение *.uprak2. Маршрутизитор ЦС ЕРЗ перемещает его, в нашем случае, в папку - C:\27\FOMS\AutoLoad\Gateway\Share\Исходящие письма\Biztalk_20000 (В зависимости от региона, у нас 20000).

**Comment by DmitryKamenev** [comment]
BizTalk, расположенный на 192.168.0.78, забирает данный файл *.uprak2 с 192.168.0.70  из C:\27\FOMS\AutoLoad\Gateway\Share\Исходящие письма\Biztalk_20000 в папку C:\foms\AutoLoad\BizTalk\Out на 192.168.0.78.

**Comment by DmitryKamenev** [comment]
Далее маршрутизатор, расположенный на 192.168.0.78, перемещает файл *.uprak2 в папку C:\foms\AutoLoad\Report\In.region, расположенную на 192.168.0.77.

**Comment by DmitryKamenev** [comment]
[Протокол.docx](https://github.com/nOleg/FOMS/files/1487752/default.docx)

**Comment by DmitryKamenev** [comment]
UPDATE FOMS_DEV_01.dbo.ReportAccess
 SET AccessDate = '2017-11-21'
WHERE Region = 20000
 Сервер 192.168.0.102, БД - FOMS_DEV_01

**Comment by nOleg** [comment]
И используй лучше отчеты MED или PHN. Эти новые отчеты (протоколы), по факту, должны быть сделаны по аналогии с ними.

**Comment by DmitryKamenev** [comment]
Отчет POL_ISS 
Путь: /Reports2/autorized_journal_region_report
Параметры:
month (Тип int), 
year (Тип smallint)
region (Тип smallint)

Отчет PHN_RATE
Путь: /Reports2/AttachmentSexAgeRegionReport 
Параметры:
InsuranceTerritory (тип int)
OnDate (Тип DateTime)
