### ISSUE TITLE
Пункт ЧТЗ 3. Доработка выгрузки в zip архив xml файлов

### ISSUE THREAD

**Issue by DmitryKamenev** [nOleg/FOMS#7]
В данный момент все xml-файлы выгружаются в один zip архив. В ЧТЗ указано, что для каждой территории страхования выгружается отдельный файл. Необходимо для каждого файла формировать отдельный zip-архив с именем аналогично xml файла.

**Comment by nOleg** [comment]
Иван Владимирович подтвердил первую модель(все в одном).
