### ISSUE TITLE
Создать динамическую заглушку

### ISSUE THREAD

**Issue by nOleg** [nOleg/FOMS#9]
Брать файлы из папки
\\192.168.0.40\public\FRMR_REST
Если одноименного файла нет создается исключения снислс не найден. 
Отфильтровать результаты в диапазоне дат

**Comment by nOleg** [comment]
Иван Владимирович модернизирет txt/json заглушки (файлы не json)

**Comment by DmitryKamenev** [comment]
Файл со СНИЛС для проверки.

[YM2017001.zip](https://github.com/nOleg/FOMS/files/1440805/YM2017001.zip)
